#!/usr/bin/env ansible-playbook
---
- name: deploy Sparkline
  hosts: all
  strategy: free
  gather_facts: false
  vars:
    project: sparkline
    env: prod
    slug: "{{ project }}-{{ env }}"
    prefix: /var/www/{{ slug }}
  tasks:
    - name: remove existing virtualenv
      file: path="{{ prefix }}/.venv" state=absent
      tags: full

    - name: upload directory {{ playbook_dir }} to {{ prefix }}
      synchronize: src="{{ playbook_dir }}/" dest={{ prefix }}

    - name: create cache and tools directories
      file: path={{ item }} state=directory owner=www-data
      loop:
        - /var/www/.local
        - /var/www/.cache
        - /var/www/.config
        - /var/www/.ansible
        - "{{ prefix }}/.venv"
      tags: full

    - name: cleanup UV cache
      command: uv cache clean
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data
      tags: full

    - name: create virtualenv
      shell: uv venv -q
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data
      tags: full

    - name: install dependencies
      shell: uv sync --frozen || uv sync --frozen --refresh
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data

    - name: install supervisor config
      file: state=link src={{ prefix }}/supervisor-{{ env }}.conf dest=/etc/supervisor/conf.d/{{ slug }}.conf
      tags: full

    - name: restart process
      supervisorctl: name="{{ slug }}" state=restarted
      tags: restart
