[project]
name = "sparkline"
version = "0.1.0"
description = "A service for generating sparkline graphs"
authors = [
  { name="Alexander Ryabov", email="alex.ryabov@gmail.com" },
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "matplotlib>=3.10.0",
    "sentry-sdk>=2.19.2",
    "uvicorn[standard]>=0.34.0",
    "aiomcache>=0.8.2",
]

[tool.ruff]
line-length = 150
target-version = "py312"
